# Generated by Django 5.1.4 on 2026-10-07 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('text', 'Text'), ('code', 'Code snippet'), ('equation', 'Equation'), ('image', 'Image'), ('graph', 'Graph'), ('table', 'Table'), ('video', 'Video'), ('audio', 'Audio')], max_length=20)),
                ('state', models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('ta_review', 'Waiting for TA'), ('flagged', 'Flagged'), ('prof_review', 'Waiting for professor'), ('revising', 'AI revising'), ('approved', 'Approved'), ('exported', 'Exported')], db_index=True, default='processing', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('flag_reason', models.TextField(blank=True)),
                ('source_ref', models.JSONField(blank=True, default=dict)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_nodes', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='uploads.parseddocument')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='classes.class')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='classes.lecture')),
            ],
            options={
                'ordering': ['lecture', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NodeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('author_type', models.CharField(choices=[('ai', 'AI'), ('person', 'Person')], max_length=10)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='review.node')),
            ],
            options={
                'ordering': ['node', 'number'],
            },
        ),
        migrations.AddField(
            model_name='node',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='review.nodeversion'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='review.node')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='review.nodeversion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('edit', 'Edit'), ('flag', 'Flag'), ('unflag', 'Unflag'), ('send_back', 'Send back'), ('regenerate', 'Regenerate')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('from_state', models.CharField(max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='review.node')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='review.nodeversion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='nodeversion',
            constraint=models.UniqueConstraint(fields=('node', 'number'), name='unique_version_number'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['klass', 'state', 'confidence'], name='review_node_klass_i_b5dd61_idx'),
        ),
    ]
