# Generated by Django 5.1.4 on 2026-10-07 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('html_s3_key', models.CharField(blank=True, max_length=500)),
                ('version_ids', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='classes.class')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='classes.lecture')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
