# Generated by Django 5.1.4 on 2026-10-07 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_name', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=20)),
                ('detected_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('s3_key', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('awaiting_upload', 'Waiting for upload'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('done', 'Done'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='awaiting_upload', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='classes.class')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='classes.lecture')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('convert', 'Convert to Markdown'), ('extract', 'Extract figures and equations'), ('process', 'AI processing')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='uploads.sourcefile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParsedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('markdown_s3_key', models.CharField(max_length=500)),
                ('assets', models.JSONField(blank=True, default=list)),
                ('xml_s3_key', models.CharField(blank=True, max_length=500)),
                ('source_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed', to='uploads.sourcefile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
